### PR TITLE
Towards fixing the unit tests

### PR DESCRIPTION
**Pull request by rdeits**
Unit tests still fail due to #14 but this seems like a useful improvement anyway.

### CODE REVIEW

**Comment by rdeits** [comment]
I've commented out (but not yet deleted) the Iteration sub-module, and brought in MLDataPattern as a requirement. As far as I can tell, the replacement for:

```julia
infinite_batches(inputs, targets, size=20)
```

is:

```julia
RandomBatches(ObsView((inputs, targets)), size=20)
```

But I'm now getting another failure: 

```
LinReg: Error During Test
  Got an exception of type MethodError outside of a @test
  MethodError: no method matching update!(::ObjectiveFunctions.RegularizedObjective{Transformations.Affine{Float64,Transformations.Params{SubArray{Float64,1,Array{Float64,1},Tuple{UnitRange{Int64}},true},Tuple{Base.ReshapedArray{Float64,2,SubArray{Float64,1,Array{Float64,1},Tuple{UnitRange{Int64}},true},Tuple{}},SubArray{Float64,1,Array{Float64,1},Tuple{UnitRange{Int64}},true}},Tuple{Tuple{Int64,Int64},Tuple{Int64}}}},ObjectiveFunctions.LossTransform{Float64,LossFunctions.LPDistLoss{2}},PenaltyFunctions.ScaledElementPenalty{Float64,PenaltyFunctions.L1Penalty}}, ::MLDataPattern.ObsView{Tuple{SubArray{Float64,1,Array{Float64,2},Tuple{Base.Slice{Base.OneTo{Int64}},Int64},true},SubArray{Float64,1,Array{Float64,2},Tuple{Base.Slice{Base.OneTo{Int64}},Int64},true}},Tuple{SubArray{Float64,2,Array{Float64,2},Tuple{Base.Slice{Base.OneTo{Int64}},Array{Int64,1}},false},SubArray{Float64,2,Array{Float64,2},Tuple{Base.Slice{Base.OneTo{Int64}},Array{Int64,1}},false}},Tuple{LearnBase.ObsDim.Last,LearnBase.ObsDim.Last}})                                                                                                             
  Closest candidates are:
    update!(::StochasticOptimization.FixedLR, ::Any) at /home/rdeits/.julia/v0.6/StochasticOptimization/src/learningrates.jl:9
    update!(::OnlineStats.StatLearn{OnlineStats.SPGD,L,P} where P<:LearnBase.Penalty where L<:LearnBase.Loss, ::Any) at /home/rdeits/.julia/v0.6/OnlineStats/src/xyinput/statlearn.jl:124
    update!(::OnlineStats.StatLearn{OnlineStats.MAXSPGD,L,P} where P<:LearnBase.Penalty where L<:LearnBase.Loss, ::Any) at /home/rdeits/.julia/v0.6/OnlineStats/src/xyinput/statlearn.jl:139
    ...
  Stacktrace:
   [1] search_direction at /home/rdeits/.julia/v0.6/StochasticOptimization/src/gradients/gradients.jl:19 [inlined]
   [2] learn!(::ObjectiveFunctions.RegularizedObjective{Transformations.Affine{Float64,Transformations.Params{SubArray{Float64,1,Array{Float64,1},Tuple{UnitRange{Int64}},true},Tuple{Base.ReshapedArray{Float64,2,SubArray{Float64,1,Array{Float64,1},Tuple{UnitRange{Int64}},true},Tuple{}},SubArray{Float64,1,Array{Float64,1},Tuple{UnitRange{Int64}},true}},Tuple{Tuple{Int64,Int64},Tuple{Int64}}}},ObjectiveFunctions.LossTransform{Float64,LossFunctions.LPDistLoss{2}},PenaltyFunctions.ScaledElementPenalty{Float64,PenaltyFunctions.L1Penalty}}, ::StochasticOptimization.GradientLearner{StochasticOptimization.FixedLR,StochasticOptimization.Adamax{Float64},StochasticOptimization.GradientAverager}, ::MLDataPattern.ObsView{Tuple{SubArray{Float64,1,Array{Float64,2},Tuple{Base.Slice{Base.OneTo{Int64}},Int64},true},SubArray{Float64,1,Array{Float64,2},Tuple{Base.Slice{Base.OneTo{Int64}},Int64},true}},Tuple{SubArray{Float64,2,Array{Float64,2},Tuple{Base.Slice{Base.OneTo{Int64}},Array{Int64,1}},false},SubArray{Float64,2,Array{Float64,2},Tuple{Base.Slice{Base.OneTo{Int64}},Array{Int64,1}},false}},Tuple{LearnBase.ObsDim.Last,LearnBase.ObsDim.Last}}) at /home/rdeits/.julia/v0.6/StochasticOptimization/src/gradients/gradients.jl:82
   [3] learn!(::ObjectiveFunctions.RegularizedObjective{Transformations.Affine{Float64,Transformations.Params{SubArray{Float64,1,Array{Float64,1},Tuple{UnitRange{Int64}},true},Tuple{Base.ReshapedArray{Float64,2,SubArray{Float64,1,Array{Float64,1},Tuple{UnitRange{Int64}},true},Tuple{}},SubArray{Float64,1,Array{Float64,1},Tuple{UnitRange{Int64}},true}},Tuple{Tuple{Int64,Int64},Tuple{Int64}}}},ObjectiveFunctions.LossTransform{Float64,LossFunctions.LPDistLoss{2}},PenaltyFunctions.ScaledElementPenalty{Float64,PenaltyFunctions.L1Penalty}}, ::LearningStrategies.MetaLearner{Tuple{StochasticOptimization.GradientLearner{StochasticOptimization.FixedLR,StochasticOptimization.Adamax{Float64},StochasticOptimization.GradientAverager},LearningStrategies.ShowStatus,LearningStrategies.Tracer{Float64},LearningStrategies.ConvergedTo{Array{Float64,1}},LearningStrategies.MaxIter}}, ::MLDataPattern.RandomBatches{MLDataPattern.ObsView{Tuple{SubArray{Float64,1,Array{Float64,2},Tuple{Base.Slice{Base.OneTo{Int64}},Int64},true},SubArray{Float64,1,Array{Float64,2},Tuple{Base.Slice{Base.OneTo{Int64}},Int64},true}},Tuple{SubArray{Float64,2,Array{Float64,2},Tuple{Base.Slice{Base.OneTo{Int64}},Array{Int64,1}},false},SubArray{Float64,2,Array{Float64,2},Tuple{Base.Slice{Base.OneTo{Int64}},Array{Int64,1}},false}},Tuple{LearnBase.ObsDim.Last,LearnBase.ObsDim.Last}},MLDataPattern.ObsView{Tuple{SubArray{Float64,1,Array{Float64,2},Tuple{Base.Slice{Base.OneTo{Int64}},Int64},true},SubArray{Float64,1,Array{Float64,2},Tuple{Base.Slice{Base.OneTo{Int64}},Int64},true}},Tuple{Array{Float64,2},Array{Float64,2}},Tuple{LearnBase.ObsDim.Last,LearnBase.ObsDim.Last}},Tuple{LearnBase.ObsDim.Last,LearnBase.ObsDim.Last},Base.IsInfinite}) at /home/rdeits/.julia/v0.6/LearningStrategies/src/metalearner.jl:23
   [4] macro expansion at /home/rdeits/.julia/v0.6/StochasticOptimization/test/runtests.jl:127 [inlined]
```

**Comment by Evizero** [comment]
did you try 

```
RandomBatches((inputs, targets), size=20)
```

**Comment by rdeits** [comment]
Yeah, that was the first thing I tried, but it produces a different data shape. The `infinite_batches` call produces 20 tuples, each of which contains one input and one target. `RandomBatches((inputs, targets))` produces a single tuple with the first element being an Array of `n_inputs x 20` and the second being an Array of `n_targets x 20`.

**Comment by Evizero** [comment]
This may be the problem: https://github.com/JuliaML/StochasticOptimization.jl/blob/master/src/gradients/gradients.jl#L24

**Comment by Evizero** [comment]
try `AbstractObsIterator` instead

**Comment by rdeits** [comment]
Yes, that worked, thanks! Next up: https://github.com/JuliaML/ObjectiveFunctions.jl/pull/3

**Comment by rdeits** [comment]
The plot thickens: https://github.com/JuliaLang/julia/issues/21719

**Comment by rdeits** [comment]
Ok, tests pass for me after cherry-picking the fix for https://github.com/JuliaLang/julia/issues/21719 so hopefully this should work on Julia v0.5 and the 0.7 nightlies.

**Comment by rdeits** [comment]
Woohoo! Travis tests are passing with nightly (but not yet with 0.6 until https://github.com/JuliaLang/julia/issues/21719 is backported)

**Comment by Evizero** [comment]
I lost track a little. Are you waiting for some merge or input from me somewhere, or where exactly did we leave off?

**Comment by rdeits** [comment]
I think this PR is ready, but it might be worth waiting to make sure the julia PR above is backported to 0.6. If it isn't, I can make a workaround.

**Comment by Evizero** [comment]
Understood. Feel free to ping me anytime

**Comment by rdeits** [comment]
Ok, tests are passing on v0.6 and v0.7. I think this is finally ready for review & merge.

**Comment by Evizero** [comment]
very nice. Thanks!

**Pull request merged**
